name: ci-demo
on:
  push
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
  build:
    needs: checkout
    runs-on: self-hosted
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew clean build
  image:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 313183373/liveness-test
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tag: ${{ steps.meta.outputs.version }}
  deploy:
    needs: image
    runs-on: self-hosted
    steps:
      - run: helm install . --generate-name --set image.tag=${{ needs.image.outputs.tag }}
